/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.reservation.system;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Addbus;
import java.sql.SQLException;
import dao.addbusDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.BillDao;
import java.io.FileOutputStream;
import model.Bill;

/**
 *
 * @author rifaa
 */
public class Bus extends javax.swing.JFrame {
    public int billId=1;
    

    public String Source;
    public String Destination;

    /**
     * Creates new form Bus
     */
    public Bus() {
        initComponents();
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        contact = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        bdes = new javax.swing.JTextField();
        bpr = new javax.swing.JTextField();
        bsource = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnbook = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus_No", "Bus_name", "Source", "Destination", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 113, 656, 157));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Source");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 134, 92, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Destination");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 186, -1, -1));

        btnsearch.setBackground(new java.awt.Color(204, 204, 204));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        btnsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsearchKeyPressed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 165, 125, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Please...", "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvanandapuram", "Thrissur", "Wayanad" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 138, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Please...", "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvanandapuram", "Thrissur", "Wayanad" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 190, -1, -1));

        contact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 363, 71, -1));

        bname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 363, 71, -1));

        bdes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(bdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 431, 71, -1));

        bpr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(bpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 431, 71, -1));

        bsource.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(bsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 431, 71, -1));

        pname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 363, 71, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Passenger Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 329, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Contact No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 329, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Bus name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 329, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Source");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 406, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Destination");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 406, 71, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 403, 43, -1));

        bno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(bno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1113, 363, 71, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Bus No");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1113, 329, 43, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact No.", "Bus name", "Bus No", "Source", "Destination", "Date", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 710, 264));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BUS LIST");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 70, 88, -1));

        btnadd.setText("ADD DETAILS");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 480, -1, -1));

        btnbook.setText("BOOK");
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        getContentPane().add(btnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 760, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addbusbackg.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String Source=(String) jComboBox1.getSelectedItem();
        String Destination = (String)jComboBox2.getSelectedItem();
        busbysearch(Source,Destination);
    
    
    
    }
        
        
        
    
    public  void busbysearch(String Source,String Destination){
         DefaultTableModel dtm= (DefaultTableModel) jTable1.getModel();
         dtm.setRowCount(0);
        ArrayList<Addbus> list = addbusDao.getBus(Source, Destination);
        Iterator<Addbus> itr = list.iterator();
        while(itr.hasNext()){
        Addbus addbusObj = itr.next();
        dtm.addRow(new Object[]{addbusObj.getBus_No(),addbusObj.getBus_name(),addbusObj.getSource(),addbusObj.getDestination(),addbusObj.getPrice()});
        
        }
    
    
    }//GEN-LAST:event_formComponentShown

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here
          String Source=(String) jComboBox1.getSelectedItem();
        String Destination = (String)jComboBox2.getSelectedItem();
       Addbus addbus = null;
        addbus = addbusDao.search(Source, Destination);
        if(addbus == null)
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:red\">No Bus Found!!!</b></html>","Message",JOptionPane.ERROR_MESSAGE);
        else {
          //   if(addbus.getStatus().equals("false")){
            //    //ImageIcon icon = new ImageIcon("src/popupicon/wait.png");
              //  //JOptionPane.showMessageDialog(null, "<html><b>Wait for admin Approval</b></html>","Message",JOptionPane.INFORMATION_MESSAGE,icon);
               //setVisible(false);
                //new Bus().setVisible(true);
                busbysearch(Source,Destination);
        }
          
                
                
                
                
            
          
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsearchKeyPressed
        // TODO add your handling code here:
        String Source=(String) jComboBox1.getSelectedItem();
        String Destination = (String)jComboBox2.getSelectedItem();
        Addbus addbus = null;
        addbus = addbusDao.search(Source, Destination);
        if(addbus == null)
           JOptionPane.showMessageDialog(null, "<html><b style=\"color:red\">No Bus Found!!!</b></html>","Message",JOptionPane.ERROR_MESSAGE);
        else {
          //   if(addbus.getStatus().equals("false")){
            //    //ImageIcon icon = new ImageIcon("src/popupicon/wait.png");
              //  //JOptionPane.showMessageDialog(null, "<html><b>Wait for admin Approval</b></html>","Message",JOptionPane.INFORMATION_MESSAGE,icon);
               
        busbysearch(Source,Destination);
        }
        
    }//GEN-LAST:event_btnsearchKeyPressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String Bus_No =model.getValueAt(index, 0).toString();
        bno.setText(Bus_No);
         String Bus_name =model.getValueAt(index, 1).toString();
        bname.setText(Bus_name);
         String Source =model.getValueAt(index, 2).toString();
        bsource.setText(Source);
         String Destination =model.getValueAt(index, 3).toString();
        bdes.setText(Destination);
         String Price =model.getValueAt(index, 4).toString();
        bpr.setText(Price);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String busname = bname.getText();
        String busno = bno.getText();
        String source = bsource.getText();
        String destination = bdes.getText();
        String name = pname.getText();
        String no = contact.getText();
        String price = bpr.getText();
        SimpleDateFormat dcn=new SimpleDateFormat("dd-12-yyyy");
        String date = dcn.format(jDateChooser1.getDate());
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name,no,busname,busno,source,destination,date,price});
        
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed
        // TODO add your handling code here:
        
        String busname = bname.getText();
        String busno = bno.getText();
        String source = bsource.getText();
        String destination = bdes.getText();
        String name = pname.getText();
        String no = contact.getText();
        String price = bpr.getText();
        SimpleDateFormat dcn=new SimpleDateFormat("dd-12-yyyy");
        String date = dcn.format(jDateChooser1.getDate());
        Bill bill=new Bill();
       bill.setId(billId);
        bill.setName(name);
        bill.setContact(no);
        bill.setDate(date);
        bill.setPrice(price);
        bill.setBusname(busname);
        bill.setBusno(busno);
        bill.setSource(source);
        bill.setDestination(destination);
       // BillDao.GetId();
        BillDao.save(bill);
        
        String path = "Downloads";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf" ));
            doc.open();
            Paragraph ticket = new Paragraph("                      Ticket Details\n");
            doc.add(ticket);
            Paragraph starline = new Paragraph("***************************************************************************\n");
            doc.add(starline);
            Paragraph paragraph1 = new Paragraph("\tTicket ID :" +billId+ "\n " );
            doc.add(paragraph1);
            doc.add(starline);
            PdfPTable tb1 = new PdfPTable(8);
            tb1.addCell("Passenger Name ");
            tb1.addCell("Contact No. ");
            tb1.addCell("Bus No. ");
            tb1.addCell("Bus Name ");
            tb1.addCell("Source ");
            tb1.addCell("Destination ");
            tb1.addCell("Date ");
            tb1.addCell("Price ");
            for(int i = 0;i<jTable2.getRowCount();i++)
            {
                String n = jTable2.getValueAt(i, 0).toString();
                String o = jTable2.getValueAt(i, 1).toString();
                String p = jTable2.getValueAt(i, 3).toString();
                String q = jTable2.getValueAt(i, 2).toString();
                String r = jTable2.getValueAt(i, 4).toString();
                String s = jTable2.getValueAt(i, 5).toString();
                String t = jTable2.getValueAt(i, 6).toString();
                String u = jTable2.getValueAt(i, 7).toString();
                tb1.addCell(n);
                tb1.addCell(o);
                tb1.addCell(p);
                tb1.addCell(q);
                tb1.addCell(r);
                tb1.addCell(s);
                tb1.addCell(t);
                tb1.addCell(u);
                
                
            }
            doc.add(tb1);
            doc.add(starline);
            OpenPdf.openbyid(String.valueOf(billId));
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new Bus().setVisible(true);
        
    }//GEN-LAST:event_btnbookActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bdes;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField bno;
    private javax.swing.JTextField bpr;
    private javax.swing.JTextField bsource;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbook;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables

    private static class Date {

        public Date() {
        }
    }
}
